# Generated by Django 4.2.7 on 2026-09-01 07:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Квартальная сетка',
            },
        ),
        migrations.CreateModel(
            name='RoadObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('object_type', models.CharField(choices=[('POLYLINE', 'Линия'), ('POLYGON', 'Полигон')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('label2', models.CharField(blank=True, max_length=500)),
                ('label3', models.CharField(blank=True, max_length=500)),
                ('type_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дорожный объект',
                'verbose_name_plural': 'Дорожные объекты',
            },
        ),
        migrations.CreateModel(
            name='RoadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('road_name', models.CharField(max_length=200, verbose_name='Автодорога')),
                ('conditions', models.TextField(verbose_name='Условия проезда')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Информация о дороге',
                'verbose_name_plural': 'Информация о дорогах',
                'ordering': ['-updated_at'],
            },
        ),
    ]
